export class VendorModel {
  /**
   * Unique identifier of this vendor (Autogenerated on DB).
   */
  vendorId: number = 0;
  /**
   * The name of the vendor.
   */
  vendorName: string = '';
  /**
   * The name of the contact person for this vendor.
   */
  contactPerson: string = '';
  /**
   * The email address of the vendor.
   */
  emailAddress: string = '';
  /**
   * The phone number of the vendor.
   */
  phoneNumber: string = '';
  /**
   * The street address of the vendor.
   */
  address: string = '';
  /**
   * A brief description or explanation of the `remarks` property.
   */
  remarks: string = '';
  /**
   * The total amount that has been paid to the vendor.
   */
  totalPaidAmount: number = 0;
  totalPayable: number = 0;
  /**
   * The total liability of the vendor.
   */
  totalRecievable: number = 0;
  totalRecieved: number = 0;
  /**
   * The unique identifier of the organization associated with this vendor.
   */
  organizationId: number = 0;
}
