export class VendorModel {
  /**
   * Unique identifier of this vendor (Autogenerated on DB).
   */
  vendorId: number = 0;
  /**
   * The name of the vendor.
   */
  vendorName: string = '';
  /**
   * The name of the contact person for this vendor.
   */
  contactPerson: string = '';
  /**
   * The email address of the vendor.
   */
  emailAddress: string = '';
  /**
   * The phone number of the vendor.
   */
  phoneNumber: string = '';
  /**
   * The street address of the vendor.
   */
  address: string = '';
  /**
   * A brief description or explanation of the `remarks` property.
   */
  remarks: string = '';
  /**
   * Total amount of money owed by this vendor (এই বিক্রেতার পাওনা টাকা মোট পরিমাণ).
   */
  totalPayable: number = 0;
  /**
   * Total amount of money owed from this vendor (এই বিক্রেতা থেকে পাওনা টাকা মোট পরিমাণ).
   */
  totalRecievable: number = 0;
  /**
   * The unique identifier of the organization associated with this vendor.
   */
  organizationId: number = 0;
}
